name: Kernel Build Non-GKI
on: 
  workflow_dispatch:
    inputs:
      REPO:
        default: 'android_kernel_samsung_a22x'
        description: 'Kernel Repo'
        type: string
      BRANCH:
        default: 'master'
        description: 'Kernel Branch'
        type: string
      DEFCONFIG:
        default: 'a22x_defconfig'
        description: 'Kernel Defconfig'
        type: string

jobs:
  build:
    permissions:
      contents: write
      actions: write
    name: Build kernel from ${{ github.actor }}
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: checkout kernel source
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          repository: '${{ github.actor }}/${{ inputs.REPO }}'
          reff: ${{ inputs.BRANCH }}
          path: kernel_root

      - name: Set Timezone && Install Dependency
        run: |
          sudo apt install device-tree-compiler -y
          sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

      - name: Setup Toolchain
        run: |
          git clone --depth=1 https://github.com/naifi1954/toolchain.git -b clang-11 clang
          git clone --depth=1 https://github.com/naifi1954/toolchain.git -b gcc-4.9 gcc
          git clone --depth=1 https://github.com/naifi1954/toolchain.git -b gcc-4.9 arm-gnu arm
          echo "CROSS_COMPILE_ARM32=$PWD/arm/bin/arm-linux-gnueabi-" >> $GITHUB_ENV
          echo "CROSS_COMPILE=$PWD/gcc/bin/aarch64-linux-android-" >> $GUTHUB_ENV
          echo "PATH=$PWD/clang/bin/clang" >> $GITHUB_ENV
        working-directory: kernel_root
          
      - name: Build kernel
        run: |
          set +e
          make ARCH=arm64 O=$PWD/out ${{ inputs.DEFCONFIG }}
          set -e
          make ARCH=arm64 O=$PWD/out -j$(nproc --all)
        working-directory: kernel_root

      - name: Kernel Information
        run: |
          echo "KV=$(zcat out/arch/arm64/boot/Image.gz | strings | grep "Linux version" )" >> $GITHUB_ENV
          echo "BUILD_DATE=$(TZ=Asia/Jakarta date +%Y%m%d)" >> $GITHUB_ENV
          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Upload To Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kernel_root/out/arch/arm64/boot/Image
            kernel_root/out/arch/arm64/boot/Image.gz
          name: Kernel Samsung A22 5G
          tag_name: ${{ github.run_id }}
          body: |
            Build Date: `${{ env.BUILD_DATE }}`
            Linux Version: `${{ env.KV }}`
            Commit: Most recent [commit](https://github.com/${{ github.actor }}/${{ inputs.REPO }}/commit/${{ env.COMMIT_ID }}) during building.
