name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v6
      with:
        repository: 'rufnx-prjkt/android_kernel_samsung_a22x'
        ref: 'master'
        path: rootdir
        show-progress: false
        fetch-depth: 1

    - name: Prepare timezone fix
      run: |
        sudo rm -f /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

    - name: Build Kernel
      run: |
        cd rootdir
        git clone --depth=1 https://github.com/naifi1954/toolchain.git -b clang-12 ./clang
        git clone --depth=1 https://github.com/naifi1954/toolchain.git -b gcc-4.9 ./gcc
        ./clang/bin/clang --version

        export PATH="$(pwd)/clang/bin:$(pwd)/gcc/bin:$PATH"
        export CC="ccache clang"
        export CROSS_COMPILE=aarch64-linux-android-
        export CLANG_TRIPLE=aarch64-linux-gnu-

        make -j$(nproc) O=out ARCH=arm64 a22x_defconfig
        make -j$(nproc) O=out ARCH=arm64 CC="$CC" CROSS_COMPILE="$CROSS_COMPILE" CLANG_TRIPLE="$CLANG_TRIPLE"

        if [ -f ./out/arch/arm64/boot/Image.gz ]; then
          echo "Build Success"
          cd kernel_root
          git clone --depth=1 https://github.com/naifi1954/AnyKernel3.git -b a22x AK
          cp ./out/arch/arm64/boot/Image.gz AK
          cd AK && zip -r9 ../AnyKernel3-a22x.zip *
        fi

    - name: Upload to Release
      uses: softprops/action-gh-release@v3
      with:
        files: |
          kernel_root/*.zip
        name: Kernel Samsung A22 5G
        tag_name: ${{ github.run_id }}
        body: |
          ## Releases
      
